### ISSUE TITLE
Error on dropping privileges is silently omitted when not in debug mode 

### ISSUE THREAD

**Issue by pxlpnk** [feross/downgrade#1]
This is dangerous as one would not be notified of it and would in the worst case run in the more privileged user/group.
https://github.com/feross/downgrade/blob/master/index.js#L14-L19

**Comment by feross** [comment]
@pxlpnk You are correct - we should be more aggressive about the error when in production mode.

When in development, I don't want this module to throw exceptions, since then the user would need to use `try-catch` around it and throw the error away. So an exception is only thrown when `NODE_ENV=production`.

**Comment by feross** [comment]
Published as 1.1.0.
